on: 
  push:
    tags: [ "*" ]

name: CI

jobs:
  build_and_test:
    name: build all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_target: 
          - "x86_64-unknown-linux-gnu"
          - "x86_64-pc-windows-gnu"
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.build_target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.build_target }} --release
      - run: ls -R
      - uses: actions/upload-artifact@master
        with:
          name: build_${{ matrix.build_target }}
          path: |
            target/${{ matrix.build_target }}/release/geoconverter.exe
            target/${{ matrix.build_target }}/release/geoconverter

  release:
    name: create release
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - uses: actions/download-artifact@master
        with:
          path: artifacts

      - run: ls -R artifacts

      - name: Make Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/*/geoconverter*
